config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :sites do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
      resources :events do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple,
                                    on: :collection,
                                    as: :destroy_multiple
      end
    end
    resources :site_categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :home_images do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users

      get '/categories', to: 'categories#index'

      # Api User
      get '/users/:id', to: 'users#user_profile'
      post '/users/:id/edit', to: 'users#edit_profile'

      # Api Sites
      get '/search', to: 'sites#search'
      get '/sites/:id', to: 'sites#site_profile'

      # Eventos
      get '/sites/:site_id/events', to: 'events#index'
      get '/sites/:site_id/events/:id', to: 'events#show'

      scope 'sites/:site_id' do
        resources :comments, only: [:create, :destroy]
        post '/like', to: 'socials#likes'
        post '/check', to: 'socials#checks'
      end
    end
  end

  # Errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard
  mount KepplerGaDashboard::Engine, at: '/', as: 'dashboard'
end

app/models/site_category.rb
#Generado por keppler
require 'elasticsearch/model'
class SiteCategory < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploader :icon_white, IconUploader
  mount_uploader :icon_color, IconUploader
  validates_presence_of :name, :description, :icon_color, :icon_white
  validates_uniqueness_of :name
  has_many :sites, dependent: :destroy

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(name: :asc)
    else
      self.order(name: :asc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { name: "asc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
      description:  self.description.to_s,
    }.as_json
  end

  def white_icon
    icon_white.url
  end

  def color_icon
    icon_color.url
  end

end
#SiteCategory.import

app/controllers/site_categories_controller.rb
#Generado con Keppler.
class SiteCategoriesController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_site_category, only: [:show, :edit, :update, :destroy]

  # GET /site_categories
  def index
    site_categories = SiteCategory.searching(@query).all
    @objects, @total = site_categories.page(@current_page), site_categories.size
    redirect_to site_categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /site_categories/1
  def show
  end

  # GET /site_categories/new
  def new
    @site_category = SiteCategory.new
  end

  # GET /site_categories/1/edit
  def edit
  end

  # POST /site_categories
  def create
    @site_category = SiteCategory.new(site_category_params)

    if @site_category.save
      redirect_to @site_category, notice: 'La categoría fue creada satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /site_categories/1
  def update
    if @site_category.update(site_category_params)
      redirect_to @site_category, notice: 'La categoría fue actualizada satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /site_categories/1
  def destroy
    @site_category.destroy
    redirect_to site_categories_url, notice: 'La categoría fue eliminada satisfactoriamente.'
  end

  def destroy_multiple
    SiteCategory.destroy redefine_ids(params[:multiple_ids])
    redirect_to site_categories_path(page: @current_page, search: @query), notice: "Categorías eliminadas satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_category
      @site_category = SiteCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def site_category_params
      params.require(:site_category).permit(:name, :description, :icon_white, :icon_color)
    end
end

app/helpers/site_categories_helper.rb
module SiteCategoriesHelper
end

app/views/site_categories/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} En este módulo se administrarán las categorías en las que se clasificarán los sitios registrados. Acá se podrá ingresar nuevas categorías, modificar, ver y eliminar categorías ya registradas.

app/views/site_categories/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to site_categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @site_category do |f|
					.row
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")
						= f.input :description, label: t("model.#{controller_name.singularize}.attributes.description"), input_html: {class: "materialize-textarea"}

						%label{ style: 'margin-left: 15px;' }= t("model.#{controller_name.singularize}.attributes.icon_white")
						= f.input :icon_white, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						%br
						%label{ style: 'margin-left: 15px;' }= t("model.#{controller_name.singularize}.attributes.icon_color")
						= f.input :icon_color, :as => :file_material, label: false, wrapper_html: { class: "file-field" }

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/site_categories/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, model
			= link_to edit_site_category_path(@site_category), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	- if @site_category.icon_color
		= image_tag @site_category.icon_color, id: 'category_icon'
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @site_category.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @site_category.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @site_category.description


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/site_categories/_listing.html.haml
%tr{ id: "row-#{site_category.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", site_category_path(site_category), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{site_category.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{site_category.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{site_category.id}" }

		%td{style:"width: 30%"}
			= link_to "", site_category_path(site_category, search: @query), remote: true, class: "show-row"
			%span
				= site_category.name

	%td{style:"width: 5%"}
		= link_to site_category_path(site_category), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/site_categories/edit.html.haml
= title "Categorías de Sitios - editar | #{@site_category.id}"
= render 'form'

app/views/site_categories/index.html.haml
= title("Categorías de Sitios - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_site_category_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |site_category|
				= render 'listing', site_category: site_category
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado categorías.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_site_category_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/site_categories/new.html.haml
= title "Categorías de Sitios - Nuevo"
= render 'form'

app/views/site_categories/show.html.haml
= title "Categorías de Sitios | #{@site_category.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to site_category_path(@site_category), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Está seguro de querer eliminar este registro?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, model
				= link_to edit_site_category_path(@site_category), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to site_categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			%ul.list
				%li.list-row
					= image_tag @site_category.icon_color
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @site_category.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @site_category.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= @site_category.description.to_s.humanize

app/views/site_categories/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@site_category.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");