config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :sites do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
      resources :events do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple,
                                    on: :collection,
                                    as: :destroy_multiple
      end
    end
    resources :site_categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :home_images do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users

      get '/categories', to: 'categories#index'

      # Api User
      get '/users/:id', to: 'users#user_profile'
      post '/users/:id/edit', to: 'users#edit_profile'

      # Api Sites
      get '/search', to: 'sites#search'
      get '/sites/:id', to: 'sites#site_profile'

      # Eventos
      get '/sites/:site_id/events', to: 'events#index'
      get '/sites/:site_id/events/:id', to: 'events#show'

      scope 'sites/:site_id' do
        resources :comments, only: [:create, :destroy]
        post '/like', to: 'socials#likes'
        post '/check', to: 'socials#checks'
      end
    end
  end

  # Errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard
  mount KepplerGaDashboard::Engine, at: '/', as: 'dashboard'
end

app/models/home_image.rb
#Generado por keppler
require 'elasticsearch/model'
class HomeImage < ActiveRecord::Base
  mount_uploader :img, ImageUploader
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  validates_presence_of :img

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      img:  self.img.to_s,
    }.as_json
  end

  def image
    img.url
  end

end
#HomeImage.import

app/controllers/home_images_controller.rb
#Generado con Keppler.
class HomeImagesController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_home_image, only: [:show, :edit, :update, :destroy]

  # GET /home_images
  def index
    home_images = HomeImage.searching(@query).all
    @objects, @total = home_images.page(@current_page), home_images.size
    redirect_to home_images_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /home_images/1
  def show
  end

  # GET /home_images/new
  def new
    @home_image = HomeImage.new
  end

  # GET /home_images/1/edit
  def edit
  end

  # POST /home_images
  def create
    @home_image = HomeImage.new(home_image_params)

    if @home_image.save
      redirect_to @home_image, notice: 'La imagen fue creada satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /home_images/1
  def update
    if @home_image.update(home_image_params)
      redirect_to @home_image, notice: 'La imagen fue actualizada satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /home_images/1
  def destroy
    @home_image.destroy
    redirect_to home_images_url, notice: 'La imagen fue eliminada satisfactoriamente.'
  end

  def destroy_multiple
    HomeImage.destroy redefine_ids(params[:multiple_ids])
    redirect_to home_images_path(page: @current_page, search: @query), notice: "Imagenes eliminadas satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_image
      @home_image = HomeImage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def home_image_params
      params.require(:home_image).permit(:img)
    end
end

app/helpers/home_images_helper.rb
module HomeImagesHelper
end

app/views/home_images/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"}
			En este módulo se podrá gestionar las imagenes que se mostraran al inicio de la aplicación.
			%br Actualmente está limitada a 5 imágenes.

app/views/home_images/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to home_images_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @home_image do |f|
					.row
						= f.input :img, :as => :file_material, label: false, wrapper_html: { class: "file-field" }

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/home_images/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, HomeImage
			= link_to edit_home_image_path(@home_image), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-image
		= image_tag @home_image.img


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/home_images/_listing.html.haml
.col.s4
	.card.home-images-card
		.card-image
			= image_tag home_image.img
		.item-check
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{home_image.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{home_image.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{home_image.id}" }
		= link_to home_image_path(home_image), class: "btn-floating waves-effect btn-flat pull-right" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/home_images/edit.html.haml
= title "Imágenes de inicio - editar | #{@home_image.id}"
= render 'form'

app/views/home_images/index.html.haml
= title("Imágenes de inicio - Listado")
.listing.col.l9.m12.s12
	- if can?(:new, model) && @objects.size <= 4
		= link_to new_home_image_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	- if @objects.size.zero?
		%table.bordered
			%tbody
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado Imágenes.
	- else
		.images-box
			- @objects.each do |home_image|
				= render 'listing', home_image: home_image

	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_home_image_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/home_images/new.html.haml
= title "Imágenes de inicio - Nuevo"
= render 'form'

app/views/home_images/show.html.haml
= title "Imágenes de inicio | #{@home_image.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, HomeImage
				= link_to home_image_path(@home_image), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, HomeImage
				= link_to edit_home_image_path(@home_image), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to home_images_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-image
				= image_tag @home_image.img

app/views/home_images/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@home_image.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");