config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :sites do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
      resources :events do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple,
                                    on: :collection,
                                    as: :destroy_multiple
      end
    end
    resources :site_categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :home_images do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users

      get '/categories', to: 'categories#index'

      # Api User
      get '/users/:id', to: 'users#user_profile'
      post '/users/:id/edit', to: 'users#edit_profile'

      # Api Sites
      get '/search', to: 'sites#search'
      get '/sites/:id', to: 'sites#site_profile'

      # Eventos
      get '/sites/:site_id/events', to: 'events#index'
      get '/sites/:site_id/events/:id', to: 'events#show'

      scope 'sites/:site_id' do
        resources :comments, only: [:create, :destroy]
        post '/like', to: 'socials#likes'
        post '/check', to: 'socials#checks'
      end
    end
  end

  # Errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard
  mount KepplerGaDashboard::Engine, at: '/', as: 'dashboard'
end

app/models/event.rb
# Generado por keppler
require 'elasticsearch/model'
class Event < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploader :img, ImageUploader
  validates_presence_of :name, :description, :address, :img
  validates_uniqueness_of :name
  belongs_to :site

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      search(self.query query).records.order(id: :desc)
    else
      order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query,
                               fields: [:name,
                                        :address,
                                        :description
                                       ],
                               operator: :and
                             }
             }, sort: { id: 'desc' }, size: count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: id.to_s,
      name:  name.to_s,
      address:  address.to_s,
      img:  img.to_s,
      description:  description.to_s,
      web:  web.to_s,
      site_id:  site_id.to_s,
    }.as_json
  end

  def image
    img.url
  end
end
#Event.import

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    # EventsController
    class EventsController < ApiController

      def index
        events = Event.where(site_id: params[:site_id])
        unless events.empty?
          render json: { event: events_json(events),
                                 token: user_with_token.authentication_token },
                 status: 200
        else
          render json: { message: 'No existen eventos en el sitio solicitado.' },
                 status: 200
        end
      end

      def show
        events = Event.where(site_id: params[:site_id], id: params[:id])
        unless events.empty?
          render json: { event: events_json(events),
                                 token: user_with_token.authentication_token },
                 status: 200
        else
          render json: { message: 'No existe el Evento solicitado.',
                                 token: user_with_token.authentication_token },
                 status: 200
        end
      end

      private

      def events_json(events)
        events.as_json(
          only: [:id, :name, :description,
                 :address, :web, :site_id],
          methods: [:image]
        )
      end
    end
  end
end

app/controllers/events_controller.rb
#Generado con Keppler.
class EventsController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_site

  # GET /events
  def index
    events = Event.where(site_id: @site.id).searching(@query).all
    @objects, @total = events.page(@current_page), events.size
    redirect_to events_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.site_id = set_site.id
    if @event.save
      redirect_to site_event_path(@event, site_id: @site.id), notice: 'El evento fue creado satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to site_event_path(@event, site_id: @site.id), notice: 'El evento fue actualizado satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to site_events_path, notice: 'El evento fue eliminado satisfactoriamente.'
  end

  def destroy_multiple
    Event.destroy redefine_ids(params[:multiple_ids])
    redirect_to site_events_path(page: @current_page, search: @query), notice: "Eventos eliminados satisfactoriamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_site
      @site = Site.find(params[:site_id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name, :address, :img, :description, :web, :site_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} En este módulo se administrarán los eventos que ofrecerá cada sitio registrado en el sistema. Acá se podrá ingresar nuevos eventos, modificar, ver y eliminar eventos ya registrados.

app/views/events/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to site_events_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for([@site, @event]) do |f|
					.row
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")
						= f.input :img, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :description, label: t("model.#{controller_name.singularize}.attributes.description"), input_html: {class: "materialize-textarea"}
						= f.input :address, label: t("model.#{controller_name.singularize}.attributes.address")
						= f.input :web, label: t("model.#{controller_name.singularize}.attributes.web")

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/events/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Event
			= link_to edit_site_event_path(@event, site_id: @site.id), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @event.img
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @event.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.address")
			.display-value= @event.address
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @event.description
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.web")
			.display-value= @event.web
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.site_id")
			.display-value= @event.site.name


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/events/_listing.html.haml
%tr{ id: "row-#{event.id}" }
	- if can? :destroy_multiple, Event
		%td.item-check{style:"width: 10%"}
			= link_to "", site_event_path(event, search: @query, site_id: @site.id), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{event.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{event.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{event.id}" }

		%td{style:"width: 30%"}
			= link_to "", site_event_path(event, search: @query, site_id: @site.id), remote: true, class: "show-row"
			%span
				= event.name
		%td{style:"width: 30%"}
			= link_to "", site_event_path(event, search: @query, site_id: @site.id), remote: true, class: "show-row"
			%span
				= event.web
		%td{style:"width: 30%"}
			= link_to "", site_event_path(event, search: @query, site_id: @site.id), remote: true, class: "show-row"
			%span
				= event.site.name

	%td{style:"width: 5%"}
		= link_to site_event_path(event, site_id: @site.id), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/events/edit.html.haml
= title "Eventos - editar | #{@event.id}"
= render 'form'

app/views/events/index.html.haml
= title("Eventos - Listado")


= header_information do
	= link_to "Sitios", sites_path
	= ">"
	= link_to "#{@site.name.humanize}", site_path(id: @site.id)
	= "> Eventos"

.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_site_event_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |event|
				= render 'listing', event: event
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado eventos.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_site_event_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/events/new.html.haml
= title "Eventos - Nuevo"
= render 'form'

app/views/events/show.html.haml
= title "Eventos | #{@event.id}"

= header_information do
	= link_to "Sitios", sites_path
	= ">"
	= link_to "#{@site.name.humanize}", site_path(id: @site.id)
	= link_to "> Eventos", site_events_path(site_id: @site.id)

.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Event
				= link_to site_event_path(id: @event.id), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Está seguro de querer eliminar este registro?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Event
				= link_to edit_site_event_path(id: @event.id), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to site_events_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-image
				= image_tag @event.img
			.card
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @event.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.address")
						.display-value.fs-body-1.tc-black-2= @event.address.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @event.description.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.web")
						.display-value.fs-body-1.tc-black-2= @event.web.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.site_id")
						.display-value.fs-body-1.tc-black-2= @event.site.name

app/views/events/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@event.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");