config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :sites do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
      resources :events do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple,
                                    on: :collection,
                                    as: :destroy_multiple
      end
    end
    resources :site_categories do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
    resources :home_images do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple,
                                  on: :collection,
                                  as: :destroy_multiple
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users

      get '/categories', to: 'categories#index'

      # Api User
      get '/users/:id', to: 'users#user_profile'
      post '/users/:id/edit', to: 'users#edit_profile'

      # Api Sites
      get '/search', to: 'sites#search'
      get '/sites/:id', to: 'sites#site_profile'

      # Eventos
      get '/sites/:site_id/events', to: 'events#index'
      get '/sites/:site_id/events/:id', to: 'events#show'

      scope 'sites/:site_id' do
        resources :comments, only: [:create, :destroy]
        post '/like', to: 'socials#likes'
        post '/check', to: 'socials#checks'
      end
    end
  end

  # Errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard
  mount KepplerGaDashboard::Engine, at: '/', as: 'dashboard'
end

app/models/site.rb
require 'elasticsearch/model'
# Site
class Site < ActiveRecord::Base
  mount_uploader :img, ImageUploader
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :site_category
  validates_uniqueness_of :name
  validates_presence_of :name,
                        :address,
                        :description,
                        :latitude,
                        :longitude,
                        :site_category_id
  acts_as_commentable
  acts_as_votable
  acts_as_saveable
  has_many :events, dependent: :destroy

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  def self.clean_site!
    all.map do |a|
      a.comments.delete_all
      a.votes_for.delete_all
      a.saves_for.delete_all
    end
  end

  def self.reload_index!
    __elasticsearch__.delete_index!
    __elasticsearch__.create_index!
    __elasticsearch__.import
  end

  settings analysis: {
    analyzer: {
      spanish_snowball: {
        type: 'snowball',
        language: 'Spanish',
        filter: %w(asciifolding lowercase)
      },
      autocomplete: {
        type:      'custom',
        tokenizer: 'standard',
        filter: %w(lowercase autocomplete_filter)
      }
    },
    filter: {
      autocomplete_filter: {
        type: 'edge_ngram',
        min_gram: 1,
        max_gram: 20
      }
    }
  } do
    mapping do
      [:id, :name, :category,
       :site_category_id, :address,
       :description, :category_description].each do |attribute|
        indexes attribute, type: 'string', analyzer: 'spanish_snowball'
      end
    end
  end

  def self.searching(query)
    if query
      search(self.query query).records.order(name: :asc)
    else
      order(name: :asc)
    end
  end

  def self.api_searching(query, categories)
    if query.empty? && categories.empty?
      all.order(name: :asc)
    elsif query.empty? || categories.empty?
      search(Site.query_filter_or(query, categories)).records.order(name: :asc)
    else
      search(Site.query_filter_and(query, categories)).records.order(name: :asc)
    end
  end

  def self.query(query)
    { query: { match: { _all: { query: query, fuzziness: 'auto', operator: :and } }
              }, sort: { name: 'asc' }, size: count }
  end

  def self.query_filter_or(query, array)
    {
      query: {
        bool: {
          should: [{
            match:  {
              _all: {
                query: query,
                fuzziness: 'auto'
              }
            }
          }, terms: { site_category_id: array }]
        }
      }, sort: { name: 'asc' }, size: count
    }
  end

  def self.query_filter_and(query, array)
    {
      query: {
        filtered: {
          query: {
            match:  {
              _all: {
                query: query,
                fuzziness: 'auto'
              }
            }
          }, filter: { terms: { site_category_id: array } }
        }
      }, sort: { name: 'asc' }, size: count
    }
  end

  # Armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: id.to_s,
      name: name,
      category: site_category.name,
      site_category_id: site_category.id,
      address: address,
      description: description,
      category_description: site_category.description
    }.as_json
  end

  def category
    site_category.name
  end

  def color_icon
    site_category.icon_color.url
  end

  def white_icon
    site_category.icon_white.url
  end

  def image
    img.url
  end

  def likes
    get_likes.as_json(only: [:id, :voter_id], methods: [:user_name])
  end

  def checks
    get_upsaves.as_json(only: [:id, :voter_id], methods: [:user_name])
  end

  def count_likes
    get_upvotes.size
  end

  def count_checks
    get_upsaves.size
  end

  def all_likes
    get_upvotes.as_json(only: [:id],
                        include: [{ voter: { only: [:id, :name] } }])
  end

  def all_checks
    get_upsaves.as_json(only: [:id],
                        include: [{ saver: { only: [:id, :name] } }])
  end

  def all_comments
    comments.as_json(only: [:id, :comment],
                     methods: [:likes],
                     include: [{ user: { only: [:id, :name, :url_img] }
                               }]
                    )
  end

  def all_events
    events.as_json(
      only: [:id, :name, :description, :web, :site_id],
      methods: [:image]
    )
  end
end

# Site.import

app/controllers/api/v1/sites_controller.rb
module Api
  module V1
    # SitesController
    class SitesController < ApiController

      def search
        categories = params[:categories].split(',')
                                        .map! { |a| SiteCategory.find_by_name(a) }
                                        .compact.map { |a| a.id }

        sites = Site.api_searching(params[:query], categories).all

        if sites.count.zero?
          render json: { message: 'No se encontraron resultados de búsqueda.' },
                 status: 200
        else
          render json: { sites: search_sites_json(sites),
                         token: user_with_token.authentication_token },
                 status: 200
        end
      end

      def site_profile
        site = Site.find(params[:id])
        if site
          render json: { site: site_profile_json(site),
                         token: user_with_token.authentication_token },
                 status: 200
        else
          render json: { message: 'No existe el Sitio solicitado.' },
                 status: 200
        end
      end

      private

      def search_sites_json(objects)
        objects.as_json(
          only: [:id, :name, :description,
                 :address, :facebook,
                 :twitter, :web],
          methods: [:category, :color_icon, :image, :count_likes, :count_checks]
        )
      end

      def site_profile_json(site)
        site.as_json(
          only: [:id, :name, :description, :address, :latitude,
                 :longitude, :facebook, :twitter, :web],
          methods: [:category,:white_icon, :image, :all_comments, :all_likes, :all_checks, :all_events]
        )
      end
    end
  end
end

app/controllers/sites_controller.rb
#Generado con Keppler.
class SitesController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :update, :create]

  # GET /sites
  def index
    sites = Site.searching(@query).all
    @objects, @total = sites.page(@current_page), sites.size
    redirect_to sites_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /sites/1
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  def create
    @site = Site.new(site_params)

    if @site.save
      redirect_to @site, notice: 'El sitio fue creado satisfactoriamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /sites/1
  def update
    if @site.update(site_params)
      redirect_to @site, notice: 'El sitio fue actualizado satisfactoriamente.'
    else
      render :edit
    end
  end

  # DELETE /sites/1
  def destroy
    @site.get_likes.delete_all
    @site.get_upsaves.delete_all
    @site.comments.delete_all
    @site.destroy
    redirect_to sites_url, notice: 'El sitio fue eliminado satisfactoriamente.'
  end

  def destroy_multiple
    Site.destroy redefine_ids(params[:multiple_ids])
    redirect_to sites_path(page: @current_page, search: @query),
                            notice: 'Sitios eliminados satisfactoriamente'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end


    def set_categories
      @categories = SiteCategory.order(:name)
    end

    # Only allow a trusted parameter "white list" through.
    def site_params
      params.require(:site).permit(:name, :img, :site_category_id,
                                   :address, :description, :facebook,
                                   :twitter, :web, :latitude, :longitude
                                  )
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} En este módulo se administrarán los sitios que se verán en el sistema. Acá se podrá ingresar nuevos sitios, modificar, ver y eliminar sitios ya registrados.

app/views/sites/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to sites_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @site do |f|
					.row
						= f.input :img, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")
						= f.input :description, label: t("model.#{controller_name.singularize}.attributes.description"), input_html: {class: "materialize-textarea"}
						= f.input :site_category_id, collection: @categories, label: false, include_blank: "Selecione una categoría", input_html: { class: "browser-default" }
						= f.input :address, label: t("model.#{controller_name.singularize}.attributes.address"), input_html: {class: "materialize-textarea"}
						= f.input :latitude, label: t("model.#{controller_name.singularize}.attributes.latitude")
						= f.input :longitude, label: t("model.#{controller_name.singularize}.attributes.longitude")
						= f.input :web, label: t("model.#{controller_name.singularize}.attributes.web")
						= f.input :facebook, label: t("model.#{controller_name.singularize}.attributes.facebook")
						= f.input :twitter, label: t("model.#{controller_name.singularize}.attributes.twitter")

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/sites/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :index, Event
			= link_to site_events_path(@site), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Eventos" do
				= material_icon.md_24.event_available
		- if can? :update, Site
			= link_to edit_site_path(@site), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @site.img
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @site.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @site.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.category")
			.display-value= @site.site_category.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.address")
			.display-value= @site.address
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @site.description
		- unless @site.facebook.blank?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.facebook")
				.display-value= @site.facebook
		- unless @site.twitter.blank?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.twitter")
				.display-value= @site.twitter
		- unless @site.web.blank?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.web")
				.display-value= @site.web
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.latitude")
			.display-value= @site.latitude
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.longitude")
			.display-value= @site.longitude
		- if @site.get_upvotes.size > 0
			%li.list-row
				.display-label Likes
				.display-value= @site.get_upvotes.size
		- if @site.get_upsaves.size > 0
			%li.list-row
				.display-label Checks
				.display-value= @site.get_upsaves.size

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/sites/_listing.html.haml
%tr{ id: "row-#{site.id}" }
	- if can? :destroy_multiple, Site
		%td.item-check{style:"width: 10%"}
			= link_to "", site_path(site), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{site.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{site.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{site.id}" }

		%td{style:"width: 30%"}
			= link_to "", site_path(site, search: @query), remote: true, class: "show-row"
			%span
				= site.name
		%td{style:"width: 30%"}
			= link_to "", site_path(site, search: @query), remote: true, class: "show-row"
			%span
				= site.site_category.name
		%td{style:"width: 30%"}
			= link_to "", site_path(site, search: @query), remote: true, class: "show-row"
			%span
				= site.web

	%td{style:"width: 5%"}
		= link_to site_path(site), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/sites/edit.html.haml
= title "Sitios - editar | #{@site.id}"
= render 'form'

app/views/sites/index.html.haml
= title("Sitios - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_site_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |site|
				= render 'listing', site: site
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado sitios.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_site_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/sites/new.html.haml
= title "Sitios - Nuevo"
= render 'form'

app/views/sites/show.html.haml
= title "Sitios | #{@site.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Site
				= link_to site_path(@site), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Está seguro de querer eliminar este registro?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Site
				= link_to edit_site_path(@site), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to sites_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
			- if can? :index, Event
				= link_to site_events_path(@site), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Eventos" do
					= material_icon.md_18.event_available.css_class("md-dark")
		.card
			.card-image
				= image_tag @site.img
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @site.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.category")
						.display-value.fs-body-1.tc-black-2= @site.site_category.name
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @site.description.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.address")
						.display-value.fs-body-1.tc-black-2= @site.address.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.latitude")
						.display-value.fs-body-1.tc-black-2= @site.latitude.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.longitude")
						.display-value.fs-body-1.tc-black-2= @site.longitude.to_s.humanize
					- unless @site.facebook.blank?
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.facebook")
							.display-value.fs-body-1.tc-black-2= @site.facebook.to_s.humanize
					- unless @site.twitter.blank?
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.twitter")
							.display-value.fs-body-1.tc-black-2= @site.twitter.to_s.humanize
					- unless @site.web.blank?
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.web")
							.display-value.fs-body-1.tc-black-2= @site.web.to_s.humanize
					- if @site.get_upvotes.size > 0
						%li.list-row
							.display-label Likes
							.display-value= @site.get_upvotes.size
					- if @site.get_upsaves.size > 0
						%li.list-row
							.display-label Checks
							.display-value= @site.get_upsaves.size

app/views/sites/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@site.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");